### ISSUE TITLE
Beaudar发布评论失败

### ISSUE THREAD

**Issue by Xaviw** [zsdycs/lipk.org-test#23]
在 post https://beaudar-api.lipk.org/repos/Xaviw/XaviDocs/issues 时报 503，但是仓库 issues 中已经添加了对应的issue

我在你博客中找了一篇没有评论的文章尝试也是同样的结果，请问这是什么原因呢

**Comment by zsdycs** [comment]
![image](https://github.com/zsdycs/lipk.org-vitepress/assets/44798353/3f3ac614-f188-41ac-80fe-9ddf4ccddc9f)

不要勾选这个就可以了，这个是因为 GitHub 的 issue api 在创建 issue 时，不可以带有 label，而要精确的搜索评论又只能通过 label 来存储每篇文章的“唯一值”，因为 issue api 只能精确搜索 label。

**Comment by Xaviw** [comment]
我尝试了取消 issue-label 和 label ，但是结果还是一样😅，这是我用的配置，麻烦再帮我分析下呢：

```
const script = document.createElement('script');
script.src = 'https://beaudar.lipk.org/client.js';
script.setAttribute('repo', 'Xaviw/XaviDocs')
script.setAttribute('issue-term', 'title')
script.setAttribute('comment-order', 'desc')
script.setAttribute('input-position', 'top')
script.setAttribute('crossorigin', 'anonymous')
script.async = true;
```

这是发出去的请求：

```json
{
  "labels": [
    "",
    ""
  ],
  "title": "xxx",
  "body": "xxx"
}
```

**Comment by zsdycs** [comment]
帮忙看的话，我需要在线环境，仅你目前的信息，我看不出来有什么问题，我看了你仓库中的 beaudar.json 配置，

```json
{
  "origins": [
    "https://xaviw.github.io"
  ]
}
```

我看你的这个 page 网站并没在线上，你是本地测试的嘛？如果你是在本地测试，你需要将本地的网站地址加到这个配置里去。

**Comment by Xaviw** [comment]
我是在线测试的，这是我的 [在线文档](https://xaviw.github.io/XaviDocs/) 和 [Github 仓库](https://github.com/Xaviw/XaviDocs)

Beaudar 定义在 `/components/Comment.vue` 中，麻烦帮忙看下

**Comment by zsdycs** [comment]
问题修复了，在修复问题的过程中，我发现在第一次创建 issue 时，GitHub 可以携带自定义的 labels 了，这意味着在配置 Beaudar 时，勾选 ”Issue 精确匹配标签“（即：设置 issue-label ），是完全有效的。

感谢您的 issues！
